### ISSUE TITLE
License request from pywidevine different to the one constructed on the device

### ISSUE THREAD

**Issue by thomasnal** [rlaphoenix/pywidevine#24] opened 2023-01-22 11:21 UTC
**Describe the bug**
License request constructed by pywidevine gets rejected by license server while the device itself plays the video without issue.  The situation indicates that the license server has a means to distinguish the license request constructed by pywidevine comparing to chrome on the device.

The request to license server is constructed correctly, otp, token, headers.  Confirmed by more users.  So started to wonder if there is anything that the license server can distinguish other than the key+blob since these are correct.

**To Reproduce**
Create Android device in emulator, Pixel 6 Pro, Android 11. Extract keys for CDM version 16.0.0. Construct license challenge for vdocipher license server.  Challenge has token that contains otp, playback info, href, tech, and license request.  Make a post request.

**Expected behavior**
A correctly constructed license request that will in request to license server return the license.

**Additional context**
pywidevine test succeeds.

The context may look like out of concern of pywidevine at first sight.  However, the case indicates that the license server can distinguish license request from pywidevine from android 11's chrome.  Therefore it should be a concern of pywidevine construct license request that is identical to the browser on the device.

**Comment by thomasnal** [comment] 2023-01-22 14:33
More information from new experiments. When the keys are extracted from a physical device then pywidevine creates a license request that works with the license server.  I will park this issue here since I have a solution and the issue can be either in pywidevine or the dumper (dumping fake keys?).

**Comment by rlaphoenix** [comment] 2023-01-22 15:39
What's most likely happening is the license server simply blacklisted that specific certificate. I wouldn't be surprised since it's for an emulator. If it's Android app can be installed in the Emulator I'd try run it and see if it can play anything licensed.

In cases like this for the future, also make sure that the Service Certificate is set, and using the correct one. Some services refuse if it's not set or not the right one.

However, what's most likely the issue here is simply that the system ID/serial (provision) is blacklisted. This is almost confirmed with the fact that you had another provision that worked, with no other code changes.

**Comment by thomasnal** [comment] 2023-01-22 16:28
Hey, thanks for getting back.

The service certificate is set when extracting the key.  The wvd was made with "ANDROID" argument only.

Not sure where you get that "another provision worked" or what you exactly mean by "provision".  Keys extracted from devices made by the emulator don't work at all, license server responds with auth failed.  Yet, after the auth failed,  chrome plays drm videos inside the emulator where the device runs.  So no way for me to get keys and make my own requests to the license server.

What works are keys extracted from a physical device.  It is true, the process and pywidevine is with no change.

**Comment by rlaphoenix** [comment] 2023-01-22 16:39
First, you are misunderstanding what a 'provision' is. A provision is a private key you have from a device. e.g., `device_private_key`. This combined with the Client ID blob would be a 'provision', often inaccurately referred to as simply 'keys'.

I mean "another provision worked" as you stated the provision from the Emulator does not work, but from the Android device it does. Hence you're using two provisions with the other one working.

However, you state that even after "auth failed" chrome in the emulator still successfully plays videos from the license server? Have you checked to see if it made any further successful requests thereafter? As that's quite strange.

It's also possible that the device failed (auth failed) and defaulted to a lower resolution stream that has no DRM or the weaker AES Clear Key. I'd check the manifest that the Android emulator last gets to see what DRM it supports.

**Comment by thomasnal** [comment] 2023-01-22 17:28
Cool, then as you say a provision extracted from the physical device works yet provisions from the emulator don't. Tested multiple devices and android version 9, 10, 11, 12.

I paid an attention to the point of checking if the device has been blocked after the auth failed from the license server. I used the default chrome on the device, I refreshed the bitmovin page and played the video, I load the watermark demo page from vdocipher and play their video.  This works after say 20-40 such auth failed attempts and 24+ hours since then.  Throughout and after the emulated device is able to play the videos in its browser.

When I find out how to check the manifest I will do it and be back with update. Visually there has been no visible change, large device resolution 3120x1440, so I doubt any change.

**Comment by rlaphoenix** [comment] 2023-01-22 17:35
If this is the case where the old pywidevine works but mine doesn't, can someone lead me to where you guys are testing this, where the original demo page is. It would also be great if I could get a copy of the challenge from old pywidevine, and new pywidevine, both being from the same provision. That way I can much more easily debug the reason as to what's happening.

**Comment by thomasnal** [comment] 2023-01-22 17:41
That comment about pywidevine was a bit confusing and then quickly deleted.  The comment talked about testing of pywidevine vs classic widevine but later talked about "older" pywidevine.  Would need more clarification from the author.

I test with the following videos,
* https://bitmovin.com/demos/drm
* https://www.vdocipher.com/blog/2014/12/add-text-to-videos-with-watermark/

If there is a specific older pywidevine that I could try I am happy to do it.  Let me know the commit hash or tag to checkout.

**Comment by thomasnal** [comment] 2023-01-22 18:03
client info from emulator,
```
{
  "application_name": "com.android.chrome",
  "company_name": "Google",
  "model_name": "sdk_gphone_arm64",
  "architecture_name": "arm64-v8a",
  "device_name": "emulator_arm64",
  "product_name": "sdk_gphone_arm64",
  "build_info": "google/sdk_gphone_arm64/emulator_arm64:11/RSR1.210722.002/7602718:userdebug/dev-keys",
  "widevine_cdm_version": "16.0.0",
  "oem_crypto_security_patch_level": "0",
  "oem_crypto_build_information": "OEMCrypto Level3 Code 22590 May 12 2021 23:37:56"
}
```
Will try the one referenced, if not I will need to get one from another device.

**Comment by rlaphoenix** [comment] 2023-01-22 18:12
Well from what I'm reading it's as if you only have issues with the Emulator provisions. It seems to be regardless of what version of pywidevine you're using unless I misread it. This leads me to believe what I thought earlier that it's revoked is in fact the case.

How it seems to be working somewhat after 40 calls or so like you said I'm not entirely sure unless it's fallen back to a lower resolution and was allowed. E.g., not allowed 1080p license so it tried to load lower resolutions and bitrates until it got a successful request for 480p or something. That's my best guess.

The only thing from my glance at the 2nd demo link is that the token data for OTP is sourced from an unknown place. I can't find where that data is sourced from. It seems to be timestamped 2016-03-13, so maybe it's not a true OTP and can be re-used forever. I'm not entirely sure. The Playback Info seems easy enough to generate, and so would be the href of course. So it's just the OTP and the Challenge here that are the variables in play to pay attention to.

At the end of the day, I really can't see there being an issue just by using a specific private key or client ID on pywidevine's side of the process. Therefore I really just think it's the case of vdocipher blocking the emulator provisions.

--

Again if you can generate a challenge from one code base that works, that doesn't in this pywidevine codebase, using the same provision, save both the challenges, and I'll compare the differences and see if there's anything wrong. However, I really don't think there is. I think they just block emulator ones, but maybe let's em through for lower resolutions/bitrates.

**Comment by thomasnal** [comment] 2023-01-22 18:20
Their OTP is generated by their backend on each page refresh and placed inside the page source.  OTP has TTL.  Works a couple of moments and minutes, e.g. the browser's request to the license can be repeated from cmd line.  After the TTL, the license server rejects it with `License verification failed`.

**Comment by thomasnal** [comment] 2023-01-22 18:33
How can I display the manifest?  Does this gives you idea about the quality?

<img width="631" alt="Screenshot 2023-01-22 at 19 25 52" src="https://user-images.githubusercontent.com/17355467/213933464-8a654d2a-913f-4d03-b247-ff948578126c.png">

**Comment by rlaphoenix** [comment] 2023-01-22 19:51
> > Well from what I'm reading it's as if you only have issues with the Emulator provisions. It seems to be regardless of what version of pywidevine you're using unless I misread it.
> > ...
> > However, I really don't think there is. I think they just block emulator ones ...
> 
> I would like to confirm again that the the same CDM files which were extracted from the Android emulator were used with both my test scripts, that is once with the `.wvd` file using @rlaphoenix's module and another time with WKS version.

Ok, Interesting. Can you generate a challenge from WKS version, save it, test it make sure it worked, then do the same for my pywidevine and send me the two saved challenges making sure you mark which is which? If you can, disable service certs so I can verify the client ID information as well.

**Comment by thomasnal** [comment] 2023-01-22 21:41
What device and android version you selected? I will try it too.  None of the provision of emulator worked for me, yet you say you have a working one.

```python
cdm = Cdm.from_device(device)
session_id = cdm.open()
cdm.set_service_certificate(session_id, cdm.common_privacy_cert)
```

**Comment by thomasnal** [comment] 2023-01-22 23:18
What is the emulated device and android version you created?

That sounds like the way the provision is extracted is the only difference in our setups since yours works with emulated devices.  I use the original wvdumper's or diazole's.

If that would mean it is about the provision extracted, it is even more mind boggling that wvdumper/diazole's `script.js` extracts a different provision from android 10 emulated devices versus android 10 physical device.  Since one does not work with license server and other does.

**Comment by thomasnal** [comment] 2023-01-22 23:43
Makes no sense in the end.

Done for me for now. I will do some comparison of the hooked addressed and function names next week using a physical device.  I use `arm64` image.

**Comment by thomasnal** [comment] 2023-02-07 03:19
I am pissed off. I've got a physical device, Lenovo tablet, got keys pulled out, yet keep getting Auth failed from vdocipher using pywidevine constructed wvd, while the device happily plays the videos.  Going bonkers.

**Comment by thomasnal** [comment] 2023-02-07 05:18
no magic with the lib. cdm 15.0.0, `vendor/lib/libwvhidl.so` hooked at `0xf3657000`, func `kqzqahjq`.

**Comment by thomasnal** [comment] 2023-02-07 13:57
I keep seeing the same issue all over this time with physical device. The device happily plays the videos. However, license request constructed with the challenge from pywidevine receives auth failed. I switch back and forth between the device and pywidevine requests therefore the extracted provision is valid.

I decode, print and compare payloads and headers, compare them with those on the device. I debug chrome's session running on the device. Headers and payloads match, just the challenge is constructed in wvd device,

```python
device = Device.load(wvd_path)
cdm = Cdm.from_device(device)
session_id = cdm.open()
cdm.set_service_certificate(session_id, cdm.common_privacy_cert)
challenge = cdm.get_license_challenge(
    session_id,
    PSSH(pssh),
    privacy_mode=True
)
```
The `challenge` goes to the request,
```python
token_dict = {}
token_dict['otp'] = otp
token_dict['playbackInfo'] = playback_info
token_dict['href'] = href
token_dict['tech'] = tech
token_dict['licenseRequest'] = challenge
token = json.dumps(
    token_dict.to_json(),
    cls=ComplexJsonEncoder
)
token_raw = base64.b64encode(token.encode('UTF-8')).decode('UTF-8')

headers = {
    'user-agent': 'Mozilla/5.0 (Linux; Android 10; Lenovo TB-8505X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36',
    'origin': f'{origin_url.scheme}://{origin_url.hostname}/',
    'referer': f'{origin_url.scheme}://{origin_url.hostname}/',
    'vdo-ref': video-ref
}

req = requests.post(
    'https://license.vdocipher.com/auth',
    json={'token': token_raw},
    headers=headers
)
```

Can you suggest what to debug further? I can share all of the info including the extracted provision - I will reinstall if it voids. We could move it to a private channel too.

**Comment by rlaphoenix** [comment] 2023-02-07 14:51
Doesn't the `licenseRequest` value need to be base64-encoded? You left it as bytes.

**Comment by thomasnal** [comment] 2023-02-07 19:27
I took the code from a larger generalised code-base and was making it more condensed for the post.  I lost the challenge encoding during copying. The "funky" json was doing additional checks in the original code.  The point remains the same.

I re-tested the copy below.  `token_b64` is from the chrome session on the device running the watermark demo.  This ends with `{"code":2048,"message":"Authentication failed"}`.  The device itself keeps playing the videos at the highest quality after page reload and device restart.

```python
token_dict = json.loads(base64.b64decode(token_b64))
otp = otp if otp else token_dict['otp']
playback_info = token_dict['playbackInfo']
href = token_dict['href']
tech = token_dict['tech']

device = Device.load(wvd_path)
cdm = Cdm.from_device(device)
session_id = cdm.open()
cdm.set_service_certificate(session_id, cdm.common_privacy_cert)
challenge = cdm.get_license_challenge(
    session_id,
    PSSH(pssh),
    privacy_mode=True
)
challenge_b64 = base64.b64encode(challenge).decode('UTF-8')

token_dict = {}
token_dict['otp'] = otp
token_dict['playbackInfo'] = playback_info
token_dict['href'] = href
token_dict['tech'] = tech
token_dict['licenseRequest'] = challenge_b64

token_json = json.dumps(token_dict)
token_b64 = base64.b64encode(token_json.encode('UTF-8')).decode('UTF-8')

origin_url = urlparse(mpd)
headers = {
    'user-agent': 'Mozilla/5.0 (Linux; Android 10; Lenovo TB-8505X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36',
    'origin': f'{origin_url.scheme}://{origin_url.hostname}/',
    'referer': f'{origin_url.scheme}://{origin_url.hostname}/',
    'vdo-ref': video_ref
}

req = requests.post(
    'https://license.vdocipher.com/auth',
    json={'token': token_b64},
    headers=headers
)
print(req.text)

```

**Comment by thomasnal** [comment] 2023-02-10 18:07
Looks like no one has an idea.  With the code above that constructs the challenge correctly, I conclude that faulty is either the provision being dumped or the pywidevine constructing the challenge. Both cases look at least suspicious.

The first would mean the CDM has an ability to provide a fake provision, i.e. function `kqzqahjq` on cdm15 32bit is not the right one and there is another one in the device, since the device constructs correct challenges. The dumped provision however decrypts bitmovin just fine.

The second would mean that some provisions construct good challenges, as reported by others, and some don't, as reported here and others using emulator.

**Comment by rlaphoenix** [comment] 2023-02-10 19:01
You have yet to supply a challenge that you say definitely works. If you can provide one then I can deconstruct it and see what differs. However, I'm confident it's your provisions. Some ways of dumping even L3 are generally bad. I remember one script going around actually had an error and was dumping bad data as the key. Another script faked the result.

**Comment by rlaphoenix** [comment] 2023-02-10 19:04
Are you saying the last code block you sent works for you? If so, then whats the problem?

**Comment by thomasnal** [comment] 2023-02-10 23:41
The shared code takes a generated challenge and delivers it to license server. I shared it to show that I send it to the server correctly to clear this part. The problem remains in the challenge generated by pywidevine using the provision. pywidevine test command for this provision/wvd decrypts bitmovin drm with success, the device holding the provision plays videos. That means the CDM on the device can create challenges accepted by license server.

With the bad ways of dumping L3, are you saying that a bad provision decrypts bitmovin? My provision decrypts bitmovin demo. This makes me assume the provision is good. Can you comment if there can be a bad provision that can decrypt bitmovin?

I am happy to send you the provision and challenge. The point with provisions is that I have not got a provision that gets accepted by the license server. So I don't have a case that you can debug for a difference. You have not said you want to look at my current provision.

When I started the thread, I worked with emulated devices, all provisions failed with the license server, yet the emulated devices played the drm videos. The same issue but emulated devices. I shared the experience with another guy, both of us had this issue. When he switched to a physical device, onn tv box, he confirmed that that has fixed the issue with failed auth, so I opened this thread. I got the Lenovo Tab M8 but sadly the issue has remained for me. I can just keep testing new devices.

**Comment by rlaphoenix** [comment] 2023-02-11 00:01
While you did share code to send to the license server, you can't dismiss it as the cause. For one, you have `token_b64` which could be specific to a provision, device, IP, timestamp, etc. I briefly looked at vdocipher when this issue first came up and I too couldn't find any genuine info about the token, or where it came from. Specifically the OTP in it.

Also just because bitmovin accepts it, doesn't mean other places do as well. All services can use a blacklist or whitelist on both the license server SDK and their own API front. Also, you say it plays videos on the device. We don't know if it's even using Widevine, playing the same quality you are trying to license, or even using the same provision. Even an L3 device could have it's own L3 certification, and an L3-haystack certification to fall back on. The haystack one is typically a 4443 or such System ID, and usually are mass blocked or at least limited.

> With the bad ways of dumping L3, are you saying that a bad provision decrypts bitmovin?

No, they likely cant. What I was saying is there are scripts/tools out there that either mislead or just fake results. E.g., generate random data, return data parsed/processed incorrectly, or just fake.

> I am happy to send you the provision and challenge.

Please do not share the provision. But do share a challenge generated by your device, from your device, as well as a challenge that pywidevine is generating, of which you have tried to send and failed. I will compare the two and see what differs.

> The point with provisions is that I have not got a provision that gets accepted by the license server. So I don't have a case that you can debug for a difference.

You can. You say the device itself works and plays. So just use HTTP-Toolkit and sniff the request and save the challenge that was sent to the license server. For Pywidevine just save it to a file, or base64 and print it and copy it. We want to compare challenges, not provisions.

**Comment by rlaphoenix** [comment] 2023-02-11 00:31
I've given a look at the watermark demo for vdocipher, and could only find one difference with our challenges. The request ID. Now. Here's the thing. It's up to the CDM to decide what to use for the request ID. License Servers aren't meant to dictate what format it should be but it seems like vdocipher does.

Chrome's CDM (chromecdm) just does a random 16-byte request ID, while Android OEMCrypto does a more or less strange approach. It generates 4 random bytes followed by 4 0x00 bytes. It then uses the session number in little-endian to fill up 8 more bytes. The result would usually be <4 rand><4 0x00><7 0x00><1 0x01 or small number>. From there OEMCrypto seems to have a bug as I doubt it was intentional, but they encode it incorrectly. They convert it to upper-case HEX (now 64chars in length), then encode that as base64.

Since you and I are both using Android CDMs, this is the correct request ID formula. It just seems vdocipher is trying to dictate what it should be. However, a reminder that we are comparing a Chrome challenge with an Android-like challenge. I would still need to see a real Android challenge from your physical device to really confirm what's happening.

I'll also just mention now that I too think the android formula that's currently in use is wrong. However, I've had strong pushback behind the scenes with some proof to show that Android challenges (at least some) did it like that. And yes, specifically that encoding.

What I'd be interested is to see what your Lenovo device uses as the request ID.

**Comment by thomasnal** [comment] 2023-02-11 00:33
Now I get that you want the challenge from the device and want to compare it with a challenge from pywidevine. Sure, that's easy, I will send that.

The API is clear about the OTP, input to OTP is client secret and selection of options that control restrictions, ttl, geo, etc. Important for our case, is it does not consider info about the client who will play the video.

**Comment by rlaphoenix** [comment] 2023-02-11 00:37
I tried explicitly using a similar length and encoding request ID (chrome style request ID) and it still failed. I'm also having issues with a code 2013 "timed out" response.

**Comment by thomasnal** [comment] 2023-02-11 00:47
> We don't know if it's even using Widevine, 

You want to say that the chrome browser is not using widevine?

> playing the same quality you are trying to license, 

The http request to license server does not specify the quality.

We explored the quality played by the device earlier in the thread, it plays the highest quality.

>or even using the same provision.

We rely on the hooked methods in the library being used by chrome. Assuming that since they get called these are the correct functions. Many users have reported that the provision flowing through that hooked function is a good one. So we assume this not a honey pot. But if it was a honeypot, then the extract provision would not decrypt a drm video. However, this decrypts videos. That gives us all indications that this is the provision used by the device itself.

Do you have theories or indications that the device have multiple provisions that all decrypt the video yet only selected ones get accepted by license servers?

**Comment by thomasnal** [comment] 2023-02-11 01:12
> I'm also having issues with a code 2013 "timed out" response.

OTP has time to live. It gets set by the backend when requesting the OTP. Recommended to be at least 5 minutes. Default 6 hours. The OTPs usually last a couple of minutes. The watermark demo lasts a few minutes, looks 5 minutes but I didn't test it specifically. Each HTTP request gives you new OTP.

**Comment by thomasnal** [comment] 2023-02-11 01:35
In your inbox now.

**Comment by rlaphoenix** [comment] 2023-02-11 01:54
What you sent is exactly what pywidevine is generating. It's not the challenge.

**Comment by rlaphoenix** [comment] 2023-02-11 02:01
However. I might have found out something. After a couple of calls under the same-ish code, the key will get blacklisted. But I might have found a solid fix to this entire issue. First of all, the OTP is genuinely one time use. Re-use it and your key is dead. However, how do you get the OTP? Well, it's sitting in the demo page in multiple places, but won't change for some reason. The fix? See that Origin header? Just randomize it lmfao.

```py
import base64
import json
import re
import requests
from urllib.parse import urlparse
from os import urandom

from pywidevine import Cdm, Device, PSSH


DEVICE = Device.load(r"C:\Users\Admin\AppData\Local\devine\WVDs\provision.wvd")
MPD_URL = urlparse("https://d2lrwez4x0gs00.cloudfront.net/media/aWYD1JUhUz8sh/725eff64/stream.mpd")
PSSH_ = "AAAAUnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADIiKnZkb2NpcGhlcjoxYWUzMzFlMzBjZjI0YWQ3OWY4ZTI4ZTk5MjQzNDU3M0jj3JWbBg=="


session = requests.Session()
session.headers.update({
    "Origin": f"https://{urandom(8).hex()}.com",
})


def get_otp() -> str:
    # this grabs OTP for the vdocipher demo page
    # it's important to match headers, e.t.c between the call here and the license call
    # so use a requests session to keep hold of the headers, cookies, e.t.c
    demo_page = session.get("https://www.vdocipher.com/blog/2014/12/add-text-to-videos-with-watermark/").text
    return re.search(r"<div id='vdo(20160313versIND313[^']*)'", demo_page).group(1)


cdm = Cdm.from_device(DEVICE)
session_id = cdm.open()
cdm.set_service_certificate(session_id, cdm.common_privacy_cert)
challenge = cdm.get_license_challenge(
    session_id,
    PSSH(PSSH_),
    privacy_mode=True
)

otp = get_otp()
print("OTP:", otp)

token = {
    "otp": otp,
    "playbackInfo": "eyJ2aWRlb0lkIjoiYzE0ODBkNmYwNTdiNGFlZjg5YTcwNTc4ZTdmOWQzM2UifQ==",
    "href": "https://www.vdocipher.com/blog/2014/12/add-text-to-videos-with-watermark/",
    "tech": "wv",
    "licenseRequest": base64.b64encode(challenge).decode()
}
print("Token:", token)

token_b64 = base64.b64encode(json.dumps(token).encode()).decode()

req = session.post(
    url="https://license.vdocipher.com/auth",
    json={
        "token": token_b64
    }
)
print(req.text)
```

Works like a charm! It seems as though if you keep the origin different each time you request, they won't block your provision.

The OTP? Just copy it lol.

**Comment by rlaphoenix** [comment] 2023-02-11 02:10
I'm going to close this now as it's outright confirmed not to be the challenge at cause for the issues. I think I've also given you an ample enough solution to the problem at hand. Feel free to continue the discussion if needed though.

**Closed by rlaphoenix** 2023-02-11 02:10 UTC

**Comment by thomasnal** [comment] 2023-02-11 13:38
Many thanks for checking. Sending flowers :)

**Comment by thomasnal** [comment] 2023-02-11 14:01
For more discussion, or for someone who will be interested in the future, what remains unclear about auth failed is, that the ban mechanism of the license server looks more sophisticated than just banning the provision.

The device that holds it is not affected by the ban, videos play in chrome.  Yet wvd requests from other hosts are all banned, I did requests from remote servers in addition to local computer.

Extracting the provision again, yields the same provision, so the functions keep using the same provision.

I am just saying there is something more behind the scene that led to the confused situation.

**Comment by thomasnal** [comment] 2023-02-11 14:09
Additionally, the emulator devices work too, tested Pixel C, api 29.

**Comment by rlaphoenix** [comment] 2023-02-11 14:33
To be clear, my randomized origin method worked for you? Did it work on all of your provisions? It seems once blocked, it stays blocked. But yes, you are right, it seems a bit sophisticated on how it is blocking.

Regardless, if you keep using a randomized origin to not get it blocked in the first place, it shouldn't happen again.
You should sniff your device and see how its retrieving the OTP, and what headers/cookies its using as it may be related.

**Comment by thomasnal** [comment] 2023-02-11 15:29
You were so so helpful. I needed someone with the experience to give me the final nudge. The fix was the requesting of OTP inside the script and using the single session between requests. Noticing that getting the page via requests returns the same OTP was a cherry on top.

Before, I was taking OTP from the browser only. Dumped fresh provision, blocked the license server, refreshed page, got OTP, made wvd request. Despite that got auth failed. The sophisticated ban mechanism led me to deadlock, since the provision works on the device but not via wvd and I didn't stress dumping new provisions again for further tests. I would try this again to double confirm, but it is not imporant anymore.

In chrome on device, or in chrome/firefox on local computer, you can keep sending the auth request repeatedly to the license server always receiving a success response, no ban. By sending repeatedly, I mean the single request of POST auth, not the page reload.
